# Generated by Django 4.0.4 on 2022-04-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('fire', models.CharField(max_length=50)),
                ('police', models.CharField(max_length=50)),
                ('medical', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now=True)),
                ('getmap', models.URLField()),
                ('pinned_map', models.URLField()),
            ],
        ),
    ]
