# Generated by Django 4.0.4 on 2022-04-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
